apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: hinrikk/todo-api:latest

          ports:
            - containerPort: 3000

          env:
            - name: DB_HOST
              value: "postgres-service.default.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "admin"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "tododb"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
    - port: 3000
      targetPort: 3000