name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Create docker safe image tags
      - name: Set image tag
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: hinrikk/todo-api:${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      KUBECONFIG: /home/github-runner/.kube/config
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set branch variables
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV
          echo "NAMESPACE=preview-$BRANCH_NAME" >> $GITHUB_ENV
          echo "HOSTNAME=$BRANCH_NAME.test.magicalotter.de" >> $GITHUB_ENV

      - name: Create namespace
        run: |
          kubectl create namespace $NAMESPACE \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: Debug branch variables
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG"
          echo "NAMESPACE=$NAMESPACE"
          echo "HOSTNAME=$HOSTNAME"

      - name: Run database init
        run: |
          kubectl delete job todo-db-init -n "$NAMESPACE" --ignore-not-found

          sed "s|hinrikk/todo-api:latest|hinrikk/todo-api:$IMAGE_TAG|g" \
            infrastructure/db-init.yaml \
            | kubectl apply -n "$NAMESPACE" -f -

          kubectl wait \
            --for=condition=complete \
            job/todo-db-init \
            -n "$NAMESPACE" \
            --timeout=120s

      - name: Deploy API
        run: |
          kubectl apply \
            -f infrastructure/api.yaml \
            -n $NAMESPACE

      - name: Deploy Ingress
        run: |
          sed "s|feature-test-preview.test|$HOSTNAME|g" \
            infrastructure/ingress.yaml \
            | kubectl apply -n "$NAMESPACE" -f -

      - name: Set branch-specific image
        run: |
          kubectl set image deployment/todo-api \
            todo-api=hinrikk/todo-api:$IMAGE_TAG \
            -n $NAMESPACE

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/todo-api \
            -n $NAMESPACE